// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const SUPPORTED_LOCALES: typeof import('D:/code/opencc-extension/src/utils/storage').SUPPORTED_LOCALES
  const autoSetting: typeof import('D:/code/opencc-extension/src/utils/storage').autoSetting
  const browser: typeof import('wxt/browser').browser
  const compileWhitelist: typeof import('D:/code/opencc-extension/src/utils/whitelist').compileWhitelist
  const convertAllTextNodes: typeof import('D:/code/opencc-extension/src/utils/conversion').convertAllTextNodes
  const convertSelection: typeof import('D:/code/opencc-extension/src/utils/conversion').convertSelection
  const convertText: typeof import('D:/code/opencc-extension/src/utils/conversion').convertText
  const convertTextNode: typeof import('D:/code/opencc-extension/src/utils/conversion').convertTextNode
  const convertTitle: typeof import('D:/code/opencc-extension/src/utils/conversion').convertTitle
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const hasConverted: typeof import('D:/code/opencc-extension/src/utils/conversion').hasConverted
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isLocaleCode: typeof import('D:/code/opencc-extension/src/utils/storage').isLocaleCode
  const matchesWhitelist: typeof import('D:/code/opencc-extension/src/utils/whitelist').matchesWhitelist
  const originSetting: typeof import('D:/code/opencc-extension/src/utils/storage').originSetting
  const resetCaches: typeof import('D:/code/opencc-extension/src/utils/conversion').resetCaches
  const setupAutoObserver: typeof import('D:/code/opencc-extension/src/utils/observer').setupAutoObserver
  const storage: typeof import('wxt/utils/storage').storage
  const targetSetting: typeof import('D:/code/opencc-extension/src/utils/storage').targetSetting
  const textboxSizeSetting: typeof import('D:/code/opencc-extension/src/utils/storage').textboxSizeSetting
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useSettings: typeof import('D:/code/opencc-extension/src/hooks/useSettings').useSettings
  const whitelistSetting: typeof import('D:/code/opencc-extension/src/utils/storage').whitelistSetting
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { LocaleCode } from 'D:/code/opencc-extension/src/utils/storage'
  import('D:/code/opencc-extension/src/utils/storage')
  // @ts-ignore
  export type { WhitelistEntry } from 'D:/code/opencc-extension/src/utils/whitelist'
  import('D:/code/opencc-extension/src/utils/whitelist')
}
