name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 8:00 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Update dependencies
        run: pnpm update
        
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet pnpm-lock.yaml; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: automated dependency updates"
          body: |
            This PR contains automated dependency updates.
            
            ## Changes
            - Updated dependencies to their latest versions
            - Updated pnpm-lock.yaml
            
            ## Testing
            Please verify that all workflows pass before merging.
            
            This PR was created automatically by the dependency update workflow.
          branch: dependency-updates
          delete-branch: true
          
      - name: Run tests on updated dependencies
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          pnpm install --frozen-lockfile
          pnpm exec eslint src
          pnpm exec prettier --check src
